#!/bin/sh

die () {
    echo >&2 "$@"
    exit 1
}

[ "$#" -eq 1 ] || die "1 argument required, $# provided"
echo $1 | grep -E -q '^[0-9]+$' || die "Numeric argument required, $1 provided"

folder="$1_dec"

mkdir $folder
touch $folder/input.txt
touch $folder/test_input.txt

cat << 'EOF' > $folder/part_1.py
import sys
import os

current_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(current_dir)
sys.path.append(parent_dir)

from util import timed

def get_input(filename):
    with open(filename, 'r') as file:
        pass

@timed
def main():
    data = get_input('./test_input.txt')

if __name__ == "__main__":
    main()
EOF

cat << 'EOF' > $folder/part_2.py
import sys
import os

current_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(current_dir)
sys.path.append(parent_dir)

from util import timed
from part_1 import (
    get_input
)

@timed
def main():
    data = get_input('./test_input.txt')

if __name__ == "__main__":
    main()
EOF
